[tool.poetry]
name = "Assignment-one-1"
version = "0.1.0"
description = ""
authors = ["Adwoa <gyasiadwoa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.9"
pandas = "^1.3.3"
numpy = "^1.21.1"
matplotlib = "^3.4.3"
seaborn = "^0.11.2"
scikit-learn = "^0.24.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"